services:
  app:
    build:
      context: ../../
      dockerfile: apiserver/.devcontainer/Dockerfile
    container_name: mail_categorizer_apiserver_dev
    volumes:
      - ../../:/app:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - ~/.ssh:/home/vscode/.ssh:ro
    working_dir: /app
    command: sleep infinity
