services:
  apiserver:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    container_name: mail_categorizer_apiserver_dev
    volumes:
      - ../:/apiserver:cached
    working_dir: /apiserver
    command: sleep infinity
